---
title: 'WIP sections for optimal portfolio paper'
author: 
csl: american-medical-association-brackets.csl
output:
  word_document:
    reference_docx: word-style-reference-manuscript.docx
  pdf_document: default
header-includes: 
  - \usepackage{amsfonts} 
bibliography: Blood_safety_portfolio.bib
---

\newcommand{\E}{\mathbb{E}}
\newcommand{\Prob}{\mathbb{P}}
\newcommand{\C}{\mathcal{C}}
\newcommand{\ind}{\mathbb{1}}
\newcommand{\1}{\textbf{1}}



<!--
#### W. Alton Russell^1^,  Brian Custer^2,3^, Margaret L. Brandeau^1^

<br> <br>

#### Running head: TBD

#### Word count: TBD 

<br> <br>

^1^Department of Management Science and Engineering, Stanford University, Stanford, CA

^2^Vitalant Research Institute, San Francisco, CA

^3^The University of California, San Francisco, San Francisco, CA   

<br> <br>

  

Corresponding author:   W. Alton Russell, Department of Management Science and Engineering, Stanford University, Stanford, CA, altonr@stanford.edu

<br> <br>

Abstract word count: XX

Text word count: XX

<br> <br>

Acknowledgements: Alton Russell was supported by a dissertation grant from Vitalant Research Institute as well by the Hsieh Family Fellowship, a Stanford Interdisciplinary Graduate Fellowship.



#####
-->



## 3.3 Mapping the optimal policy to prevalence

> When donor groups are identical except for the number of donors ($n_i$) and the prevalence of each TTI ($p_{ik}$), then a $k$-dimensional function $f(\textbf{p})$ mapping the prevalence by TTI to the optimal policy can be defined as follows:

$$
(\textbf{m}, \textbf{a}, z)^* = f(\textbf{p}), \quad  \text{where} \text{ } f(\textbf{p}) = {\arg\min}_{\textbf{m}, \textbf{a}, z} \E [\C(z, \textbf{m}, \textbf{a}, \textbf{p}) ].
$$

When the number of donor groups is large relative to the number of tests and modifications, it can be more efficient to solve or approximate this function than to explicitly evaluate each donor group separately.

> Because we are concerned with only one donor group, our objective function becomes:

$$
\E [\C(\textbf{p} \mid z, \textbf{m}, \textbf{a}, ) ] = (1- z )d + z \Big(w +  \textbf{a}^\top\boldsymbol{\phi} + \textbf{m}^\top \boldsymbol{\psi} + (1- s_2)(\textbf{v}_1 \circ \textbf{v}_3 \circ \textbf{p} ) \textbf{c} + gs_2 \Big),
$$

where, as defined before, $s_2$ is the probability any test returns a positive result; $\textbf{v}_1$ is a vector of the per-donation reduction in risk for each TTI $k$ from testing, and $\textbf{v}_3$ is a vector of the per-donation reduction in risk for each TTI $k$ from modifications. These quantities are given by:

$$
s_2 = 1 - \prod_{k=1}^{K} \prod_{j=1}^{J} [ (1 - p_k) (1 + a_j(q_{jk} - 1)) + p_k (1 - a_j r_{jk})]
$$

$$
\textbf{v}_1 = \begin{bmatrix}  \prod_{j=1}^J 1-r_{j1} a_j \\ \vdots \\ \prod_{j=1}^J 1-r_{jk} a_j \\ \vdots \\  \prod_{j=1}^J 1-r_{jK} a_j \end{bmatrix}, \quad
\textbf{v}_3 = \begin{bmatrix} 
    \prod_{l=1}^L 1 + m_{l} (h_{l1} - 1) \\
    \vdots \\
    \prod_{l=1}^L 1 + m_{l} (h_{lk} - 1) \\
    \vdots \\
    \prod_{l=1}^L 1 + m_{l} ( h_{lK} - 1) 
    \end{bmatrix}.
$$

We define a policy $\pi$ as a set of decision variables $\pi = (z, \textbf{m}, \textbf{a})$. For a given policy, this becomes

$$
\E [\C(\textbf{p}) \mid \pi] = (1- z)d + z \Big[w +  \textbf{a}^\top\boldsymbol{\phi} + \textbf{m}^\top \boldsymbol{\psi} + \big(1- s_2(\textbf{a},\textbf{p})\big)\big(\textbf{v}_1(\textbf{a},\textbf{p}) \circ \textbf{v}_3(\textbf{m},\textbf{p}) \circ \textbf{p} \big) \textbf{c} + gs_2(\textbf{a},\textbf{p}) \Big],
$$

and by grouping terms that are constant in $\textbf{p}$, this can be rewritten as,

$$
\E [\C(\textbf{p}) \mid \pi] =  \alpha(\pi) +  z \Big[\big(1- s_2(\textbf{a},\textbf{p})\big)\big(\textbf{v}_1(\textbf{a},\textbf{p}) \circ \textbf{v}_3(\textbf{m},\textbf{p}) \circ \textbf{p} \big) \textbf{c} + gs_2(\textbf{a},\textbf{p}) \Big].\\
\E [\C(\textbf{p}) \mid \pi] =  \alpha(\pi) +  \beta(\pi)\big(1- s_2(\textbf{a},\textbf{p})\big) \textbf{p+ gs_2(\textbf{a},\textbf{p}) \Big]. 
$$

We define a 'policy region' corresponding to $\pi$ in prevalence space as the $k$-dimensional region for which $\E [\C(\textbf{p}) \mid \pi] = \min_{\pi'} \E [\C(\textbf{p}) \mid \pi']$. For two policies $\pi_1$ and $\pi_2$, the $k$-dimensional 'pairwise decision boundary' (PDB) between their respective policy regions is the solution to $\E [\C(\textbf{p}) \mid \pi_1] = \E [\C(\textbf{p}) \mid \pi_2]$. 


Policy regions can be identified through the following procedure:

1. Solve for the PDB for each unique pairing of policies ($0.5T(T-1)$ pairs)

2. Divide the prevalence space into mutually exclusive and exhaustive PBD-regions, indexed by $g$, and identify $\Lambda_g$, the optimal policy for each region, by evaluating any point in the region ($\Lambda_g = {\arg\min}_{\Lambda} \E [\C(\textbf{p} \mid \Lambda) ]$ for any $\textbf{p}$ in PDB region $g$).

3. Aggregate PBDs for which $\Lambda_g = \Lambda_t$ into policy region $\Lambda_t$.

The term $s_2(\textbf{a}, \textbf{p})$ is a nonlinear function of $\textbf{p}$ in which each element of $\textbf{p}$ is multiplied up $j \times k$ times. As a result, $\E [\C(\textbf{p}) \mid \pi]$ can be a high-order polynomial function of $\textbf{p}$, and solving for each PDB requires solving the polynomial system ($\E [\C(\textbf{p}) \mid \pi_1] - \E [\C(\textbf{p}) \mid \pi_2] = 0$).


We can approximate the cost function $\E [\C(\textbf{p}) \mid \pi]$by ignoring the cost of removing donations testing positive ($gs_2(\textbf{a}, \textbf{p})$) and the impact of removing donations testing positive on the per-donation risk of releasing an infectious donation (the multiplier $1-s_2(\textbf{a}, \textbf{p})$). The resulting cost function is linear in $\textbf{p}$:



$$
\tilde{\E} [\C(\textbf{p}) \mid \pi] = \alpha(\pi) +  z \big(\textbf{v}_1(\textbf{a},\textbf{p}) \circ \textbf{v}_3(\textbf{m},\textbf{p}) \circ \textbf{p} \big) \textbf{c}.
$$

While $\tilde{\E} [\C(\textbf{p}) \mid \pi]$ is equavilent to $\E [\C(\textbf{p}) \mid \pi]$ for policies that exclude all tests, it will differ for policies that include testing, particularly when donations are likely to be removed by testing, which occurs when prevalence for a TTIs detected by a test is high or when a test has poor specificity. However, because this cost function is linear in $\textbf{p}$, it can be solved by the procedure above much more efficiently.

